const products = [
  {
    _id: "1",
    name: "Bass Guitar",
    image: "/images/bass.jpg",
    description:
      "Red electric bass guitar used on tour by Rob Trujillo, bassist of Metallica",
    brand: "Fender",
    category: "Bass Guitar",
    price: 666.99,
    countInStock: 1,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Drums",
    image: "/images/drums.jpg",
    description:
      "White drum set used by Lars Ulrich of Metallica, with certified blood stains on snare drum.",
    brand: "Pearl",
    category: "Drums",
    price: 599.99,
    countInStock: 2,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "Electric Guitar",
    image: "/images/electricGuitar.jpg",
    description:
      "Black electric guitar, shredded by the one and only James Hetfield of Metallica. This guitar plays itself.",
    brand: "Epiphone",
    category: "Electronic Guitar",
    price: 929.99,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "Kirk Hammet Guitar Pick",
    image: "/images/pick.jpg",
    description:
      "Certified guitar pick used by the mighty Kirk Hammet of Metallica.",
    brand: "Metallica",
    category: "Guitar Pick",
    price: 399.99,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "Metallica Live Record",
    image: "/images/record.jpg",
    description: "Metallica Live! on vynil record, signed by the entire band.",
    brand: "Metallica",
    category: "Music",
    price: 49.99,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: "6",
    name: "T-Shirt",
    image: "/images/tshirt.jpg",
    description: "Nirvana concert t-shirt",
    brand: "Nirvana",
    category: "Clothing",
    price: 29.99,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
];

export default products;
